version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Install Playwright browsers
          command: npx playwright install --with-deps
      - run:
          name: Run CURA Healthcare tests
          command: npx playwright test tests/curapages/CuraHealthcare.spec.js --reporter=list
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: playwright-report
          destination: playwright-report

workflows:
  cura-tests:
    jobs:
      - test
